create endpoint for get /api/articles/:article_id/comments
Kayphaz007/be-nc-project pull request #6
Opened 2023-06-27 14:08 UTC by Kayphaz007

2023-06-27 14:26 UTC, robert112233 requested changes
Great start Micheal, implement the missing tests and submit another PR for review 👍

2023-06-27 14:26 UTC, robert112233 commented on models/articles.models.js
> +            return Promise.reject({ status: 404, msg: "Not Found"})
Your Promise.reject will error for any valid articles with no comments, this situation is a 200 as nothing has gone wrong, you may want to invoke a check exists before you reject the promise

2023-06-27 14:26 UTC, robert112233 commented on __tests__/app.test.js
> +  });
Missing tests:

400 - Invalid request /api/articles/notanid/comments
200 - Valid article with no comments (returns [])

2023-06-28 10:48 UTC, robert112233 requested changes
You've misinterpreted my feedback, you will need a checkExists function in your code, https://notes.northcoders.com/courses/js-back-end/advanced-error-handling#sending-the-correct-response

2023-06-28 10:48 UTC, robert112233 commented on __tests__/app.test.js
> +      });
This test is great and what I asked for, but you replaced an older test that we still need! 

 test("should return error with msg Not Found for request not in database", () => {
    return request(app)
      .get("/api/articles/99999999/comments")
      .expect(404)
      } 
      
You need to implement both of these at the same time, differentiating between existing articles with no comments, and non existent articles, _both_ of these situations return empty rows [] so you need to create a function that checks the article exists first :)

2023-06-29 08:19 UTC, roisinoreilly approved these changes
nicely refactored :) great work, PR approved

2023-06-29 08:44 UTC, merged